[package]
name = "freeverb-clib"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
freeverb = { path = "../freeverb" }

[lib]
crate-type = ["staticlib"]
