[package]
name = "freeverb-gtk"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
audio_module = { path = "../../src/audio_module" }
freeverb_module = { path = "../../src/freeverb_module" }

audio_thread_priority = "0.3"
cpal = "0.13.1"
crossbeam-channel = "0.3"
gtk = "0.5"
ringbuf = "0.2.2"
