[package]
name = "freeverb-gtk"
version = "0.1.0"
authors = ["irh <ian.r.hobson@gmail.com>"]
edition = "2021"

[dependencies]
audio_module = { path = "../../src/audio_module" }
freeverb_module = { path = "../../src/freeverb_module" }

audio_thread_priority = "0.3"
cpal = "0.13.1"
crossbeam-channel = "0.3"
gtk = "0.17.1"
ringbuf = "0.2.2"
