[workspace]
resolver = "2"
members = [
  "crates/*",
  "examples/app_gtk",
  "examples/wasm",
]

[workspace.package]
edition = "2024"
authors = ["irh <ian.r.hobson@gmail.com>"]
license = "MIT"
readme = "README.md"
