[package]
name = "freeverb_module"
publish = false
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
audio_module = { path = "../audio_module" }
freeverb = { path = "../freeverb" }
num-derive = "0.4.2"
num-traits = "0.2"
