[package]
name = "freeverb-clib"
publish = false
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
freeverb = { path = "../freeverb" }

[lib]
crate-type = ["staticlib", "rlib"]
