[package]
name = "freeverb_module"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
audio_module = { path = "../audio_module" }
freeverb = { path = "../freeverb" }
num-derive = "0.2"
num-traits = "0.2"
