[package]
name = "freeverb-wasm"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
freeverb-clib = { path = "../../crates/clib"}

[lib]
crate-type = ["cdylib"]
