[package]
name = "freeverb-wasm"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
freeverb = { path = "../../src/freeverb" }
wasm-bindgen = "0.2.104"

[lib]
crate-type = ["cdylib"]
