[package]
name = "freeverb-wasm"
publish = false
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
freeverb-clib = { path = "../../crates/clib"}

[lib]
crate-type = ["cdylib"]
