[package]
name = "freeverb-wasm"
version = "0.0.1"
authors = ["Ian Hobson <ian.r.hobson@gmail.com>"]
edition = "2021"

[dependencies]
freeverb = { path = "../../src/freeverb" }
wasm-bindgen = "0.2.70"

[lib]
crate-type = ["cdylib"]
